# Generated by Django 4.2.5 on 2023-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('seating_capacity', models.IntegerField(default=4)),
                ('type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('convertible', 'Convertible')], default='sedan', max_length=20)),
                ('brand', models.CharField(default='None', max_length=30)),
            ],
        ),
    ]
