# Generated by Django 4.2.5 on 2023-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='registration_number',
            field=models.CharField(default=None, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
