# Generated by Django 4.2.5 on 2023-09-26 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 6, 4, 20, 112286, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 6, 4, 20, 112286, tzinfo=datetime.timezone.utc)),
        ),
    ]
