# Generated by Django 4.2.5 on 2023-09-26 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0004_alter_car_created_at_alter_car_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_column='source', max_length=100)),
                ('destination', models.CharField(db_column='destination', max_length=100)),
                ('journey_start_date', models.DateField(db_column='journey_start_date')),
                ('journey_end_date', models.DateField(db_column='journey_end_date')),
                ('car', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
