# Generated by Django 4.2.5 on 2023-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='journey_end_date',
            field=models.DateTimeField(db_column='journey_end_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='journey_start_date',
            field=models.DateTimeField(db_column='journey_start_date'),
        ),
    ]
